name: manga_easy_ranking
description: Micro app de ranking do manga easy app.
version: 1.0.0
publish_to: none
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manga_easy_sdk:
    git:
      url: https://github.com/manga-easy/manga_easy_sdk.git
      ref: v1.2.1
  coffee_cup:
    git:
      url: https://github.com/manga-easy/manga_easy_coffee_cup.git
      ref: v1.0.0
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.0.0
  manga_easy_routes:
    git:
      url: https://github.com/manga-easy/manga_easy_routes.git
      ref: v1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
